# Generated by Django 4.1.7 on 2023-03-29 04:54

import ckeditor.fields
import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=5000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=5000, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=5000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('formID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('questionID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=255)),
                ('homeBackgroundColour', colorful.fields.RGBColorField()),
                ('homeTextColour', colorful.fields.RGBColorField()),
                ('logo', models.ImageField(upload_to='')),
                ('introText', models.CharField(max_length=10000)),
                ('introImage', models.ImageField(upload_to='')),
                ('topBannerImage', models.ImageField(upload_to='')),
                ('bottomBannerImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('jobID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('requirements', ckeditor.fields.RichTextField(max_length=50000)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(max_length=50000)),
                ('jobType', models.CharField(default='', max_length=250)),
                ('duration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('purpose', models.TextField()),
                ('targetMarketInfo', models.TextField(blank=True, null=True)),
                ('slogan', models.CharField(max_length=255)),
                ('projectColour', colorful.fields.RGBColorField()),
                ('projectTextColour', colorful.fields.RGBColorField()),
                ('logo', models.ImageField(upload_to='')),
                ('servicePrices', ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True)),
                ('projectImage', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('memberID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
                ('iconImage', models.ImageField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('applicationID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=2000, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=2000, null=True)),
                ('reasonToHire', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('coverLetter', models.FileField(upload_to='coverLetters/')),
                ('applicationStatus', models.CharField(choices=[('processingResume', 'Processing'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='processingResume', max_length=100)),
                ('jobPost', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.jobpost')),
            ],
        ),
    ]
