# Generated by Django 4.1.7 on 2023-04-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='duration',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='ProjectName',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='jobType',
            field=models.CharField(max_length=255),
        ),
    ]
