# Generated by Django 4.1.7 on 2023-04-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_projectname_jobpost_projectname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementpage',
            old_name='facebook',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='announcementpage',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='announcementpage',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='announcementpage',
            name='twitter',
        ),
        migrations.AddField(
            model_name='announcementpage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcementpage',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
